name: 🧪 Test

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
    paths-ignore:
      - "docs/**"
      - "**/README.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "🧪 Test: (Node: ${{ matrix.node }})"
    strategy:
      fail-fast: false
      matrix:
        node:
          - 16
          - 18

    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          check-latest: true
          node-version: ${{ matrix.node }}

      - name: Disable GitHub Actions Annotations
        run: |
          echo "::remove-matcher owner=tsc::"
          echo "::remove-matcher owner=eslint-compact::"
          echo "::remove-matcher owner=eslint-stylish::"

      - name: 📥 Install deps
        run: yarn --frozen-lockfile

      - name: 🔬 Lint
        run: yarn lint

      - name: 🧪 Run tests
        run: yarn test
